// ==================== Recommendations ====================

// From GET /analysis/{room}/recommendations
// Stored in screeps-advisor-recommendations DynamoDB table
export interface Recommendation {
  id: string;
  roomName: string;
  createdAt: number;          // timestamp ms
  expiresAt?: number;         // TTL timestamp (seconds)
  status: 'pending' | 'applied' | 'dismissed' | 'stale' | 'resolved_helpful' | 'resolved_unhelpful';

  // Content (generated by analysis-engine Claude call)
  category: 'spawning' | 'economy' | 'optimization' | 'defense' | 'expansion' | 'behavior';
  priority: number;           // 1 (highest) - 5 (lowest)
  title?: string;
  description: string;
  evidence?: string;

  // Code context (when available)
  codeFile?: string;          // e.g. "src/spawning/utilitySpawning.ts"
  currentCode?: string;
  suggestedFix?: string;
  patternType?: string;       // e.g. "ENERGY_DRAIN", "HAULER_SHORTAGE"

  // Feedback
  feedback?: FeedbackPayload;
  feedbackAt?: number;
}

export interface FeedbackPayload {
  action: 'applied' | 'dismissed' | 'helpful' | 'unhelpful';
  comment?: string;
}

// ==================== Signals ====================

// From GET /analysis/{room}/signals
export interface SignalResponse {
  roomName: string;
  hours: number;
  dataPoints: number;
  events: SignalEvent[];
  eventCount: number;
  trends: Record<string, TrendInfo>;
  latestMetrics: Record<string, number> | null;
}

export interface SignalEvent {
  type: 'THRESHOLD' | 'ANOMALY' | 'TREND_CHANGE';
  metric: string;           // e.g. "energyStored", "cpuBucket", "hostileCount"
  value: number;
  threshold?: number;        // for THRESHOLD events
  baseline?: number;         // for ANOMALY events
  trend?: string;            // for TREND_CHANGE events
  severity: 'info' | 'warning' | 'alert' | 'critical';
  description?: string;
  timestamp: number;
  gameTick?: number;
  snapshotTimestamp?: number;
}

// From GET /analysis/{room}/signals/events
export interface SignalEventResponse {
  roomName: string;
  hours: number;
  events: SignalEvent[];
  eventCount: number;
}

export interface TrendInfo {
  start: number;
  end: number;
  delta: number;
  percentChange: number;
  trend: 'increasing' | 'decreasing' | 'stable';
}

// ==================== Observations ====================

// From GET /analysis/{room}/observations
// Stored in screeps-advisor-observations DynamoDB table
// Generated by analysis-engine or claude-analyzer Lambda
export interface ObservationResponse {
  roomName: string;
  observations: ObservationRecord[];
  count: number;
}

export interface ObservationRecord {
  id: string;
  roomName: string;
  timestamp: number;
  snapshotTick: number;
  snapshotHash: string;
  summary: string;

  observations: Observation[];
  patterns: ObservedPattern[];
  signalCorrelations: SignalCorrelation[];
  changesFromPrevious?: string | null;
}

export interface Observation {
  category: 'economy' | 'defense' | 'expansion' | 'optimization' | 'spawning' | 'behavior' | 'population' | 'infrastructure' | 'anomaly';
  observation?: string;       // from analysis-engine format
  summary?: string;           // from claude-analyzer format
  details?: string;           // from claude-analyzer format
  significance?: 'low' | 'medium' | 'high';
  confidence?: number;        // 0.0 - 1.0 (claude-analyzer format)
  dataPoints?: string[];
  relatedEntities?: string[];
}

export interface ObservedPattern {
  id?: string;
  description: string;
  confidence?: 'low' | 'medium' | 'high' | number;
  trend: 'improving' | 'stable' | 'declining' | 'worsening' | 'new' | 'resolved';
  firstSeen?: number | null;
  occurrences?: number;
  evidence?: string;
}

export interface SignalCorrelation {
  signals?: string[];
  metric?: string;
  correlation?: string;
  observation?: string;
  hypothesis?: string;
}

// ==================== Patterns (Detected) ====================

// From GET /analysis/{room}/patterns
// These are the programmatically-detected patterns from detectPatterns()
export interface PatternResponse {
  roomName: string;
  patterns: DetectedPattern[];
}

export interface DetectedPattern {
  id: string;
  type?: string;              // e.g. "ENERGY_DRAIN", "HAULER_SHORTAGE"
  severity: 'low' | 'medium' | 'high' | 'critical';
  message: string;
  description?: string;
  data?: Record<string, unknown>;
  // From observation layer:
  trend?: string;
  occurrences?: number;
  firstSeen?: number;
}
